apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  labels:
    app.kubernetes.io/managed-by: chant
    chant.intentius.io/stack: app-b
    chant.intentius.io/env: local
    app: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
        - name: web
          image: nginxinc/nginx-unprivileged:1.27-alpine
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: '25m'
              memory: '32Mi'
            limits:
              cpu: '100m'
              memory: '64Mi'

---
apiVersion: v1
kind: Service
metadata:
  name: app-b
  labels:
    app.kubernetes.io/managed-by: chant
    chant.intentius.io/stack: app-b
    chant.intentius.io/env: local
spec:
  selector:
    app: app-b
  ports:
    - port: 80
      targetPort: 8080
