// Generated by chant — do not edit directly.
// Source: prod-apply.op.ts
import { proxyActivities, condition, defineSignal, setHandler, upsertSearchAttributes } from '@temporalio/workflow';
import { TEMPORAL_ACTIVITY_PROFILES } from '@intentius/chant-lexicon-temporal/config';
import type * as activities from './activities';

const { shellCmd } = proxyActivities<typeof activities>(
  TEMPORAL_ACTIVITY_PROFILES.fastIdempotent,
);

export async function prodApplyWorkflow(): Promise<void> {
  upsertSearchAttributes({"OpName":["prod-apply"]});

  // Phase: Build
  upsertSearchAttributes({ Phase: ["Build"] });
  await shellCmd({"cmd":"./node_modules/.bin/chant build src --lexicon aws -o template.json"});

  // Phase: Deploy
  upsertSearchAttributes({ Phase: ["Deploy"] });
  await shellCmd({"cmd":"aws cloudformation deploy --template-file template.json --stack-name behold-writes-prod --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset"});

}
